[versions]
kotlin = "1.8.0"
androidGradlePlugin = "7.0.4"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidCore = { group = "androidx.core", name = "core-ktx", version.ref = "kotlin" }
